// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-expenses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-expenses.ts
var dateStr = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD");
var list_expenses_default = defineTool({
  name: "list_expenses",
  title: "List expenses",
  description: "List the signed-in user's expenses, optionally filtered by date range, category or owner.",
  inputSchema: {
    start_date: dateStr.optional().describe("Start date (inclusive), YYYY-MM-DD."),
    end_date: dateStr.optional().describe("End date (inclusive), YYYY-MM-DD."),
    category: z.string().optional().describe("Category, e.g. Food, Milk, Transport."),
    owner: z.enum(["husband", "wife"]).optional().describe("Who spent it."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, category, owner, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("expenses").select("id,date,category,amount,description,owner,payment_method").order("date", { ascending: false }).limit(limit ?? 100);
    if (start_date) q = q.gte("date", start_date);
    if (end_date) q = q.lte("date", end_date);
    if (category) q = q.eq("category", category);
    if (owner) q = q.eq("owner", owner);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const expenses = (data ?? []).map((e) => ({
      id: e.id,
      date: e.date,
      category: e.category,
      amount: Number(e.amount),
      description: e.description,
      owner: e.owner,
      payment_method: e.payment_method
    }));
    const total = expenses.reduce((s, e) => s + e.amount, 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ total, count: expenses.length, expenses }) }],
      structuredContent: { total, count: expenses.length, expenses }
    };
  }
});

// src/lib/mcp/tools/add-expense.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var add_expense_default = defineTool2({
  name: "add_expense",
  title: "Add expense",
  description: "Add a new expense for the signed-in user. Dates cannot be in the future.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Expense date, YYYY-MM-DD."),
    category: z2.string().trim().min(1).max(50).describe("Category, e.g. Food, Milk, Transport, Other."),
    amount: z2.number().positive().max(1e7).describe("Amount in rupees."),
    owner: z2.enum(["husband", "wife"]).describe("Who spent it."),
    payment_method: z2.enum(["cash", "card", "online"]).optional().describe("Defaults to cash."),
    description: z2.string().max(500).optional().describe("Optional note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const today = new Date(Date.now() + 14 * 3600 * 1e3).toISOString().slice(0, 10);
    if (input.date > today) throw new ToolError("Expense date cannot be in the future.");
    const { data, error } = await supabaseForUser(ctx).from("expenses").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      category: input.category,
      amount: input.amount,
      owner: input.owner,
      payment_method: input.payment_method ?? "cash",
      description: input.description ?? null
    }).select("id,date,category,amount,owner,payment_method,description").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const expense = { ...data, amount: Number(data.amount) };
    return { content: [{ type: "text", text: `Added \u20B9${expense.amount} for ${expense.category} on ${expense.date}.` }], structuredContent: { expense } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cqzsszhzqfcczstxwvak";
var mcp_default = defineMcp({
  name: "expense-dashboard",
  title: "Expense Dashboard",
  version: "0.1.0",
  instructions: "Tools for the signed-in user's family expense tracker (amounts in Indian Rupees). Use `list_expenses` to read and total expenses by date range, category or owner (husband/wife), and `add_expense` to record a new one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_expenses_default, add_expense_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
